# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0da39d242f804b62a931f4134e2c9597f9a003b82a64e5b4906299a498c664501b1e3912de49e38731dad47dfeb651b46d3c3bffb6871081f64ae120006610b

test:
  secret_key_base: 1dc4bc4b74615a0c84639b8f245d54f51fc3c8b8b20cb9048d26db59077913d0fd4977dde0ca95ea51518ae98085add85a838f9fe71ec3388c94656e572cda79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
